#!/bin/sh
#
# ibus-waitzar - Burmese Input for iBus
#
# Copyright (c) 2009 Seth N. Hetu <sorlok_reaves@yahoo.com>
#
# This file is part of ibus-waitzar.
#
# ibus-wiatzar is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
#
# ibus-waitzar is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ibus-waitzar.  If not, see <http://www.gnu.org/licenses/>.

# Based on:
# ibus-tmpl, copyright 2007-2008 Peng Huang <shawn.p.huang@gmail.com>
# GPL2

prefix=/usr
exec_prefix=${prefix}
libexecdir=${prefix}/lib/ibus-waitzar
pyexecdir=${exec_prefix}/lib/python2.6/site-packages
export PYTHONPATH=${exec_prefix}/lib/python2.6/site-packages:$PYTHONPATH
export IBUS_WAITZAR_LOCATION=/usr/share/ibus-waitzar
export LIBEXECDIR=$libexecdir

#Release 
exec python /usr/share/ibus-waitzar/engine/main.py $@

#Debug
#exec python /usr/share/ibus-waitzar/engine/main.py > /home/sethhetu/.wz/log.txt 2> /home/sethhetu/.wz/err.txt $@

